### ISSUE TITLE
OnJoin callback isn't fired on windows 7.

### ISSUE THREAD

**Issue by GamerUntouch** [discordapp/discord-rpc#93] opened 2017-12-10 22:04 UTC
Assuming the problem is related to windows 7 at least.
While I receive the callback on my main PC (windows 10), I don't receive it on my laptop (windows 7).
It isn't being ignored or anything, the api is simply never receiving the call. It DOES receive the ready() callback though, which is odd.

**Comment by StrikerMan780** [comment] 2018-01-09 19:49
I can vouch. A few of my Windows 7 users don't get OnJoin callbacks whatsoever.

**Comment by msciotti** [comment] 2018-01-09 19:57
I'll boot up a VM and do my best to reproduce with the sample console app.

**Comment by msciotti** [comment] 2018-01-10 21:21
@StrikerMan780 the green arrow thing seems...odd. The only requirements for that is:

- Do you have a joinSecret
- Do you have a partyId
- Do you have partySize/partyMax

If you have a user with that issue repeatedly, you should have them open up their Discord console and see if there's anything weird. Check `SetActivity` calls for errors, data that doesn't look right, etc.

**Comment by StrikerMan780** [comment] 2018-01-11 10:02
Yes to all three of those questions. The people with the bug seem to not
have any Rich presence activity at all (Discord behaves like nothing is
being played), despite the program not having any error when trying to
connect to Discord and getting a "ready" callback.

On Jan 10, 2018 5:21 PM, "Mason Sciotti" <notifications@github.com> wrote:

@StrikerMan780 <https://github.com/strikerman780> the green arrow thing
seems...odd. The only requirements for that is:

   - Do you have a joinSecret
   - Do you have a partyId
   - Do you have partySize/partyMax

If you have a user with that issue repeatedly, you should have them open up
their Discord console and see if there's anything weird. Check SetActivity
calls for errors, data that doesn't look right, etc.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/discordapp/discord-rpc/issues/93#issuecomment-356740590>,
or mute the thread

**Comment by msciotti** [comment] 2018-01-11 18:25
Is it possible that these users have two instances of Discord running without realizing it, and RPC is connecting to the client they aren't focusing? Are they doing anything outside of "normal" use, i.e. running stuff in a VM?

**Comment by StrikerMan780** [comment] 2018-01-12 20:32
Well, turns out having "Display currently running game as a status message" prevents them from being able to invite people.

As for another thing I encountered that has no explanation: Some people still aren't getting join callbacks, and some also just see "Game has ended" in the invite immediately, never giving them a chance to join, where other people in the same lobby still see it available to join.

**Comment by StrikerMan780** [comment] 2018-02-10 18:33
Yeah, I can confirm... nobody on windows 7 is getting join callbacks, but can host fine. Regardless of settings.

**Comment by msciotti** [comment] 2018-02-11 18:30
OK, I really appreciate your diligence in these issues. This and other Windows 7 oddities are the next thing I'll tackle (praying that the Ask to Join bug is fixed with a recent update I mentioned in that issue).

**Comment by msciotti** [comment] 2018-02-16 00:36
So I did some debugging on my own, and was not able to reproduce. That doesn't mean that this _isn't_ an issue, but I'll need to do more digging.

I tried to repro using a couple live, free-to-play games: [Holodrive](http://store.steampowered.com/app/370770/Holodrive/) and [Unturned](http://store.steampowered.com/app/304930/Unturned/). In both cases, a user on Windows 7 was able to join a game created by me on Windows 10.

If your users see an issue with either of those games as well, that would be an excellent point of reference for my debugging.

**Comment by StrikerMan780** [comment] 2018-02-22 17:02
Try this. You'll need your own copy of Duke Nukem 3D's duke3d.grp though.
https://gitlab.com/mossj32/EDuke32-OldMP_Maintenance/tags/eduke32-oldmp_release_12

**Comment by codecat** [comment] 2018-02-27 19:09
@msciotti You mention "other Windows 7 oddities", can you elaborate on this? Are they separate issues not related to this particular issue? I'm asking because I'm also having some issues, unsure if they're Windows 7 specific or not.

**Comment by msciotti** [comment] 2018-02-27 21:01
Mostly outlined in this thread, from Strikerman noting that some Windows 7 users aren't showing Rich Presence status, some aren't getting join callbacks. Some get joincallbacks if the game is running, but not from a cold start, etc.

I have a Windows 7 machine getting delivered on Thursday for testing purposes so I can try and put this to bed once and for all (previously been relying on less than ideal VMs). 

If you have other explicit issues, please open issues here with repro steps. The heart of this is figuring out whether these are platform issues, SDK issues, or individual implementation quirks.

**Comment by codecat** [comment] 2018-02-27 21:27
I will open a separate issue for that. I did some research I don't believe my problem to be a Windows 7 specific one.

**Comment by msciotti** [comment] 2018-03-09 01:40
OK, back with some news. We seem to have a bug in our native code for launching games that is specific to Windows 7. I have successfully reproduced the issue on Windows 7 100% of the time. 

If you are a user on Windows 7, and you are trying to interact with a join invitation when the game is _closed_ on your computer, the game will launch, but the `ACTIVITY_JOIN` event will never be received.

If you already have the game open, the failure case in launching the game never occurs, and you successfully receive the join event.

 We will get on a fix for this, and hopefully can mark this issue as resolved.

**Comment by msciotti** [comment] 2018-03-12 22:41
I'm sure I've said these exact words before, but _I think this is fixed now_. The latest version of our Canary client should no longer eat events because game launches """"failed"""". @GamerUntouch or @StrikerMan780, could either of you confirm with a user on your end for me? And I can mark this resolved.

**Comment by msciotti** [comment] 2018-03-23 17:36
Haven't heard back and can no longer reproduce locally, so will close this.

**Closed by msciotti** 2018-03-23 17:36 UTC
Labels: bug

**Comment by codecat** [comment] 2018-03-29 10:08
I'm on Windows 7, and not getting join callbacks on the Canary build while the game is already open. It loads infinitely after clicking the Join button:

![](https://i.imgur.com/Kwo77sF.png)

No callback seems to be fired in the game. In the Discord console, I only see received/emitted messages with `SET_ACTIVITY` when I click the button.

**Comment by msciotti** [comment] 2018-03-29 17:13
OK, few questions:

1. What does the `SET_ACTIVITY` payload look like from the hosting user?

2. Though I'm 1000% sure you already are, you're running `Discord_RunCallbacks()` to actually have them fire, yes? I know it's a trite question, but hey, cover all your bases lol

3. Does the callback fire if the game is closed when you hit the button? That is, will the game open and the callback fire? Or it just opens and does nothing?

3b. If it opens and does nothing, do you see any sort of console error like "Game Launch failed, exited with status code 1"?

**Comment by codecat** [comment] 2018-03-29 17:44
1. Here's what it looks like for the hosting user:
<img width="325" alt="screen shot 2018-03-29 at 19 37 10" src="https://user-images.githubusercontent.com/136534/38104183-b39adca2-3388-11e8-86ac-0efeb5f8bd98.png">

2. Yes, I'm running the callbacks, of course :D

3. Yes, it does open the game, but of course it launches it directly from Steam (which does not have rich presence in yet) rather than my development build. (I guess I can avoid that by manually registering it with Discord using a non-Steam command, which I can test tomorrow.)

**Comment by msciotti** [comment] 2018-03-29 21:09
@codecat Uhhh 🤔 Are you rolling your own lib from the master branch, or using one of the releases? Maybe I broke something...

**Comment by msciotti** [comment] 2018-03-29 21:35
So, master was broken, as was the latest release. Rolling a new one right now. If you were using one of those, apologies for the headscratching @codecat.

I wasn't properly subscribing to the RPC events on `Init()`, but it will now.

**Comment by codecat** [comment] 2018-03-29 22:11
I'm using the master branch, yeah. Thanks for the fix! I'll test it out tomorrow!

**Comment by codecat** [comment] 2018-03-30 12:57
That fixed it, thanks! :D
