### ISSUE TITLE
[Unity] Using DiscordRpc.Respond returns code 4012 "no join request for that user"

### ISSUE THREAD

**Issue by rawkjs** [discordapp/discord-rpc#64] opened 2017-11-24 21:35 UTC
Currently trying to add Discord RPC to our game in Unity and for some reason DiscordRpc.Respond always ends up popping an error with code 4012, even when my requestCallback is simple (view example below).

``` 
private void OnRequestCallback(DiscordRpc.JoinRequest request)
{
    DiscordRpc.Respond(request.userId, DiscordRpc.Reply.Yes);
}
```

My party stats are setup properly (partyId, partySize, partyMax) and my joinSecret is set to my partyId but encrypted with aes256.

The request to join button is shown properly to another user that's been added as a test user of our app.

That error code doesn't make much sense either considering I'm responding to a request callback.

**Comment by GamerUntouch** [comment] 2017-11-26 20:16
Having this issue as well, seemingly random when it works as well. (Not using unity here, made a custom wrapper for Game Maker).

**Comment by night** [comment] 2017-11-26 22:46
This error occurs when the client is not aware of a join request from a user. If you wait too long to respond to a join request (more than 30 seconds) it will timeout on our client.

**Comment by rawkjs** [comment] 2017-11-26 23:30
Yeah that's what I would expect it to be, but the issue is that I get this error when responding immediately after receiving a joinRequest callback. So I would assume the client is aware of that request.

**Comment by night** [comment] 2017-11-26 23:47
When you look at our client after receiving a join request it should show a notice bar at the top of the client. If that bar is showing it should not be possible to receive this error unless the user ID being passed back doesn't match the user id showing in the client.

**Comment by rawkjs** [comment] 2017-11-27 14:22
I did a series of tests and here's what I could make out of it :

- If my game, my discord client and my requester's Discord client are freshly restarted, the request will work properly and I'll be able to accept or refuse properly.
- If my game client has received 2 requests from the same client in the same run, the game invite will appear in the Discord client but disappears instantaneously and I get a code 4012 when responding.
- If my game is running fresh and I receive a request from someone I already have received a request from, without I or him restarting our Discord clients, the request shows up in my Discord and seems like it is available but as soon as I respond, I get a 4012.

So it seems like something gets stuck when a request has already been received by a given person.

**Comment by msciotti** [comment] 2017-11-27 17:51
I'm seeing a similar issue from other developers @night. Going to try and reproduce with @rawkjs steps above.

**Comment by msciotti** [comment] 2017-11-27 18:27
@rawkjs In your reproduction steps, when you say "the request shows up in my Discord/will appear in the Discord client," are you attempting the entire flow with Discord-only and not responding to the SDK with in-game UI?

Just so I can clarify my testing steps.

**Comment by rawkjs** [comment] 2017-11-27 18:48
@msciotti I just tried doing it from the Discord UI and it seems to work properly when the requests don't start disappearing as they get in. If I respond to those apparently valid requests through the RPC SDK instead I get the 4012.

**Comment by msciotti** [comment] 2017-11-30 00:09
@rawkjs to clarify, everything works if done only from the Discord side. But responding via the SDK gets you the 4012?

We pushed some changes late Tuesday night regarding some bugs we had in joining logic. Can you confirm that your issue persists? If so, then we'll go from there.

**Comment by StrikerMan780** [comment] 2017-11-30 02:49
Having this problem, even in non-unity apps.

**Comment by rawkjs** [comment] 2017-11-30 13:28
I can confirm that the JoinCallback isn't triggered on the person joining either when hitting "Yes" through discord. I was testing on the 2.01 version I'll build the latest and see if I still have these issues.

**Comment by msciotti** [comment] 2017-11-30 17:54
Alright. Your implementation and logic seems sane. We will try and boot up a new Unity app and see if we can reproduce.

**Comment by msciotti** [comment] 2017-11-30 18:06
@rawkjs @StrikerMan780 can you two also confirm that _all_ of the users who are trying to use Ask to Join have been whitelisted for your app? Both the requester and the receiver?

I'm sure they are; just doing do diligence.

**Comment by StrikerMan780** [comment] 2017-12-01 01:23
Yes, they are whitelisted.

**Comment by rawkjs** [comment] 2017-12-01 01:31
In my case both users I've tested with are whitelisted. I am not, but I'm the creator of the app (if that changes anything).

And also, no callback when joining through an invite or when asking to join either. Still testing with the 2.0.1 build

I'm having a hard time building the latest version and am currently in a rush so I won't be able to take the time to get this working and test it on the latest build.

**Comment by GamerUntouch** [comment] 2017-12-01 18:23
Issue on my end isn't fixed even after patching.
Some more details though.

If I call Discord_Respond through a function I have, it doesn't work.
but If I call Discord_Respond through same function I'm running Discord_RunCallbacks through, it seems to work.

I'll run some more tests to see what's causing this.

**Comment by msciotti** [comment] 2017-12-01 18:25
@GamerUntouch that's really interesting behavior. Definitely let us know if you can isolate it.

**Comment by GamerUntouch** [comment] 2017-12-01 19:20
Got it narrowed down.
If I call Discord_Respond every frame (30 FPS) it works, but if I manually call it, it doesn't seem to work. Is the request getting culled from discord's servers a couple milliseconds after the request is called? Changing the game to 1 FPS stops it from working.

**Comment by msciotti** [comment] 2017-12-05 01:09
So, after doing some tooling around with the repo's default Unity example, I'm _still_ not able to repro this issue.

If you open this repo's default Unity example, are you able to successfully receive and respond to ATJ requests between two machines?

I just did this myself this morning, and it works for me on both a macbook and a windows machine.

**Comment by GamerUntouch** [comment] 2017-12-05 17:47
Instead of using my app, I decided to compile the send_presence.c example straight from cmake and it's still giving me the issue.
Is it something to do with users?

**Comment by msciotti** [comment] 2017-12-07 19:54
I haven't been able to get solid repro steps, but my hunch is that this is a rate limiting issue.

As mentioned in the documentation, there is a 1 update per 15 second rate limit to Discord's servers. It's possible that spamming the hell out of `UpdatePresence()` calls and then trying to receive join requests could cause this behavior. Your local client would say "Yup I'm up to date we're good" while the server that fans out your presence to other users still thinks you're about 30 `UpdatePresence()` calls in the past.

My working theory of "hit the button in the button-clicker example and then try to handle a request" was not fruitful, so I'll continue looking for a real reproduction.

**Comment by msciotti** [comment] 2017-12-08 00:18
There are not, no. Even in the case where a user asks to join and then hits "nevermind" at the top of their discord client, you can still respond to the request. They will just never receive the secret.

**Comment by GamerUntouch** [comment] 2017-12-10 01:23
After some testing, I've 100% found out what's causing the problem.
Occasionally the client ignores requests, the "<user> would like to join! Yeah Nah" header doesn't appear in my discord client. If it does appear, it doesn't give me the error, otherwise it does.
Seems that the problem has something to do with the discord client rather than the RPC in this case.

**Comment by StrikerMan780** [comment] 2017-12-21 04:50
While I solved the issue of not getting join callbacks, it seems I still get "no join request for that user" when I respond yes if someone asks to join.

**Comment by msciotti** [comment] 2017-12-21 18:47
Yeah the logic is sane. We are pretty certain that it's tied to a rate limiting thing, and I've experienced getting the error myself in testing. I can't get a solid reproduction using our sample app. 

@GamerUntouch's response is more of a symptom than a cause—the symptom being that requests seem to "disappear" from Discord. If you look side by side with your game UI and the Discord client, you'll probably see that when Untouch's scenario occurs, you'll get an error.

We're working to figure out a 100% repro step in order to debug, but we haven't found one yet. I don't think we need any more "me too" comments here unless you can provide a step by step repro of the bug.

**Comment by gro-ove** [comment] 2018-01-03 19:59
Same error, happens quite often. This is how communication with that pipe looks like (I use custom library to communicate with Discord’s pipe because, unfortunately, `discord-rpc.dll` just crashes short time after a join request):

    20:56:50.558: Read: Frame; {"cmd":"DISPATCH","data":{"user":"avatar":"267c97d7c8f1bf20c18e7898d120b464","discriminator":"4342","id":"395654492135358465","username":"Devoted siskin"}},"evt":"ACTIVITY_JOIN_REQUEST","nonce":null}
    20:56:52.079: Replying to request: Yes
    20:56:52.080: Write: Frame; {"args":{"user_id":"395654492135358465"},"cmd":"SEND_ACTIVITY_JOIN_INVITE","nonce":5}
    20:56:52.080: Message written
    20:56:52.081: Read: Frame; {"cmd":"SEND_ACTIVITY_JOIN_INVITE","data":{"code":4012,"message":"no join request for that user"},"evt":"ERROR","nonce":5}
    20:56:52.081: Response is here

Maybe, of course, I forgot some important steps there, but as far as I can tell from the code, there is nothing special app should write there between `ACTIVITY_JOIN_REQUEST` and `SEND_ACTIVITY_JOIN_INVITE`.

In Discord window, it looks like that panel appears, but stays much shorter than 30 seconds. [Here is a video of it](https://drive.google.com/file/d/11S-qXOAXGd7YkSJRF4uZ-39C9zM9S-Ux/view?usp=sharing), and in it, the delay is actually not that short. Sometimes, it’s even shorter than that.

**Comment by msciotti** [comment] 2018-01-03 20:52
@gro-ove that is a really good video for us, thank you. This is high priority on our bug fix list.

**Comment by msciotti** [comment] 2018-02-10 18:53
OK, so this was some _real_ bullshit of a bug to track down, but I think we finally have a fix. I am very sorry that it's taken so long.

The "good" news is that it was a Discord client bug, and not an SDK bug. So there should be no need to update the SDK in your game to get the fix.

The fix was merged on Friday, and should be deployed to our Canary client within the next few days. I will comment here again when it's deployed to canary, and hopefully folks having this issue can install it and try for me.

**Comment by msciotti** [comment] 2018-02-12 18:25
OK, I have confirmed on my machine with the latest Discord Canary build that the 100% error repro I had before is now gone.

If anyone in this thread had this issue, please make sure you or anyone with the issue is on the most up to date Canary build, and give it a try. And please let me know if it is solved.

You can download our Canary client if you don't have it at:

Mac: https://discordapp.com/api/download/canary?platform=osx
Windows: https://discordapp.com/api/download/canary?platform=win

**Comment by msciotti** [comment] 2018-02-13 21:43
OK, after many moons, I am marking this issue closed and resolved. Thank you everyone for your patience, as I know this has been sitting around for a while.

**Closed by msciotti** 2018-02-13 21:43 UTC
Labels: bug
