### ISSUE TITLE
Discord RPC seems not working on Ubuntu 18.04?

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [discordapp/discord-rpc#213] opened 2018-08-06 05:48 UTC
I installed some apps that utilizes Discord RPC.

E.g. JetBrains IDEs Discord Rich Presence Integration
Visual Studio Code Discord Rich Presence Integration

both of them seems fail to work.
![screenshot from 2018-08-06 13-48-38](https://user-images.githubusercontent.com/25037295/43699021-71213bde-997f-11e8-8f31-775cc3d161a8.png)

**Comment by kkirigaya** [comment] 2018-08-06 06:02
The IntelliJ IDEA plugin is known to not be working. The proper issue to post on is [here](https://github.com/sorenbug/discord-intellij/issues/18). It hasn't been updated for a few months so I suggest using an earlier version or forking and compiling your own that works.

**Comment by MinnDevelopment** [comment] 2018-08-06 08:34
I just want to point out that the plugin works perfectly mine on my Ubuntu 18.04. Make sure that neither intellij or discord are installed through snap (software center).

**Comment by msciotti** [comment] 2018-08-06 16:59
^ +1 to the installed through snap comment. They do some sandboxing that messes with our filepath registration stuff.

**Comment by Vatuu** [comment] 2018-08-06 17:53
I can confirm that my discord-rpc wrapper works flawlessly after we've did some major re-structuring, on UNIX and Win64/86. But macOS is still not functional. The latest version is 1.5.1.

**Comment by msciotti** [comment] 2018-08-24 00:53
I'm going to close this issue if that's alright. Seems like the answer is here. If you are experiencing a different problem, please feel free to re-open.

**Closed by msciotti** 2018-08-24 00:53 UTC

**Comment by HelloWorld017** [comment] 2018-10-23 10:57
discordjs/RPC#36 says that path to Discord IPC in Ubuntu 18.04 is `/run/user/1000/snap.discord/discord-ipc-{Id}`, not `/run/user/1000/discord-ipc-{Id}`.

**Comment by MinnDevelopment** [comment] 2018-10-23 14:00
To quote myself: 
> Make sure that neither intellij or discord are installed through snap (software center).

**Comment by vsimitsis** [comment] 2018-11-24 11:57
For those who want to keep the snaps installed...There is this solution for Vscode. Just update this specific file https://github.com/AliDeym/RPC/blob/8dbf59006ab6b43ee13004116cb13912a5d5d1f5/src/transports/IPC.js

**Comment by ionadev** [comment] 2019-03-02 11:52
Experiencing Same Issue!

OS- Ubuntu 18.04 LTS

**Comment by msciotti** [comment] 2019-03-04 18:19
@ionadev is Discord installed through snap for you? The paths to create socket connections won't work, as it's not checking for the snap directory.

**Comment by ionadev** [comment] 2019-04-06 10:57
@msciotti Actually I Use Discord Canary, so it wasn't installed from snap, but atom was installed with snap, when i reinstalled atom from their website, the problem was sorted!

**Comment by viktorashi** [comment] 2021-08-01 23:08
For anybody that it doesn't work for: I got it working, by just uninstalling vscode and installing it back,

**BEWARE THOUGH, AS IT WILL DELETE ALL YOUR SETTINGS AND EXTENSIONS, IT'S GONNA BE LIKE BEFORE YOU INSTALLED IT AND WENT THROUGH THE COSTUMIZATION PROCESS, VERY ANNOYING.**



1. Uninstall VsCode
2. Install It back Up
3. Install the [rich presence plugin](https://marketplace.visualstudio.com/items?itemName=icrawl.discord-vscode) again.
4. You should be done I hope

 _NOT DISCORD_, but Vscode,
