### ISSUE TITLE
joinGame not getting fired

### ISSUE THREAD

**Issue by tylerhasman** [discordapp/discord-rpc#266] opened 2019-01-21 07:35 UTC
My game doesn't seem to be getting any events.
I am doing callbacks every two seconds.
My game is in Java using LibGDX and I am using this library: https://github.com/MinnDevelopment/java-discord-rpc

Any ideas?

**Comment by MinnDevelopment** [comment] 2019-01-21 08:53
Dupe of #196

**Comment by tylerhasman** [comment] 2019-01-21 09:19
I think that one is related to steam, we don't use steam.

**Comment by MinnDevelopment** [comment] 2019-01-21 09:35
I would argue its just another cause for the same issue then

**Comment by Vatuu** [comment] 2019-01-21 13:50
We're currently experiencing the same issue with our java wrapper, it seems like it is indeed an issue on the native binaries side.

**Comment by msciotti** [comment] 2019-01-21 20:17
@tylerhasman are you getting _any_ events? You marked the issue as `joinGame()` but said you aren't getting any events, so just wanna make sure it's clear.

I'm fine with having two issues open. We haven't really policed this too tightly anyway. Code snippets or sample min repro projects are always appreciated.

**Comment by tylerhasman** [comment] 2019-01-21 21:06
I get the ready event and after that I get nothing until I reset my handlers before each polling.
I am guessing this has something to do with multi-threading because when I setup a mini-demo of the discord RPC functionality it worked fine. However, in my game I need to always reset the handlers.

Here is my code below that works:
```

handlers.errored = new DiscordEventHandlers.OnStatus() {
            @Override
            public void accept(int errorCode, String message) {
                Gdx.app.error("DiscordError", errorCode+" "+message);
            }
        };

        handlers.disconnected = new DiscordEventHandlers.OnStatus() {
            @Override
            public void accept(int errorCode, String message) {
                Gdx.app.error("DiscordDisconnect", errorCode+" "+message);
            }
        };


        handlers.joinGame = new DiscordEventHandlers.OnGameUpdate() {
            @Override
            public void accept(String secret) {
                getClient().sendMessage(new DiscordJoinGameMessage(secret));
            }
        };

        handlers.joinRequest = new DiscordEventHandlers.OnJoinRequest() {
            @Override
            public void accept(DiscordUser request) {
                getChatBox().addMessage(Color.GRAY, request.username+"#"+request.discriminator+" is asking to join your game, check your Discord to accept or decline their request.");
            }
        };

        discord.Discord_UpdateHandlers(handlers);

        discord.Discord_RunCallbacks();

```
and here is how I am initializing it:
```

        DiscordEventHandlers handlers = new DiscordEventHandlers();

        handlers.ready = new DiscordEventHandlers.OnReady() {
            @Override
            public void accept(DiscordUser user) {
                Gdx.app.log("DiscordUser", user.userId+"::"+user.username);
            }
        };

        String appId = "XXXXX";

        discord.Discord_Initialize(appId, handlers, true, null);

        discord.Discord_ClearPresence();
```

and yes I am polling for events every 500ms

If I initialize the rpc with all the handlers they dont get called later, only the ready does. If I reset them before every poll they get called fine...

**Comment by msciotti** [comment] 2019-11-27 22:00
Old issue so doing some cleaning. At the time, I believe this was eventually fixed with dynamic handler registration:

https://github.com/discordapp/discord-rpc/pull/135

We've not gotten any recent reports about join events not firing, so closing this.

---

Unrelated: this SDK has been deprecated in favor of our new GameSDK, which includes many more features for developers. Find it here:

https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide

If you need help, come join us in the Discord at https://discord.gg/discord-gamesdk !

**Closed by msciotti** 2019-11-27 22:00 UTC
