### ISSUE TITLE
[Feature Request] HTTP API

### ISSUE THREAD

**Issue by Kampfkarren** [discordapp/discord-rpc#97] opened 2017-12-12 22:06 UTC
Due to the inadequate closure of the [last issue](https://github.com/discordapp/discord-rpc/issues/11) not showing signs of being reopened, I am going to restate the need for an HTTP API. 

An HTTP API would be helpful as not all game engines give access to sockets, but *do* give access to HTTP requests. An HTTP API would be helpful in this scenario. As I stated in the last thread, this could have the downside of not having access to buttons (like join and spectate), as long polling is not a viable solution.

**Comment by msciotti** [comment] 2017-12-12 22:16
Thank you for opening a separate issue, so that current issues can be kept to scope.

I am happy to keep this issue open as the official request for an HTTP-interaction with the SDK, and de-dupe others into this one.

That being said, I don't believe this is going to happen in the near future. It would require a large re-work of our presence system on which Rich Presence is built.

I am curious—which engine are you working with that _doesn't_give you access to some sort of socket API?

**Comment by crmarsh** [comment] 2017-12-12 22:33
It's for web programmers. Within browsers they can open websockets, but not named pipes. It wouldn't work too well with how Discord tracks what process is a game -- which is changeable but not how it works right now.

**Comment by boynedmaster** [comment] 2017-12-12 22:49
@msciotti Aye, I've been beating around the bush about that [for a reason](http://wiki.roblox.com/index.php?title=API:Class/HttpService) 😛

**Comment by Tenrys** [comment] 2018-03-28 10:15
Same goes for [Garry's Mod](http://wiki.garrysmod.com/page/http/Post).

With fiddling around, the closest we were to achieving Rich Presence on it was using JavaScript on a browser created on the game client to use the Discord client's websocket, however I think we need a whitelisted Discord app to make it work currently, as we're hitting an "Invalid Origin" error, related to the RPC Origin field I assume.

**Comment by msciotti** [comment] 2018-03-28 20:43
So, I learned something today as I was working on documentation for our new [Certified Devices](https://discordapp.com/developers/docs/topics/certified-devices) stuff. Our RPC socket will accept POST requests for a small subset of whitelisted commands, `SET_ACTIVITY` being one of them.

The semantics around a "full" implementation of Rich Presence via HTTP are beyond what I can think of off the top of my head—no way to get callbacks, for example—but presence updates are possible. I needed to push a fix for this a few hours ago, so it may not work immediately as the changes roll to our clients, but this is an avenue that can be taken.

**Closed by msciotti** 2018-03-28 20:43 UTC
Labels: feature-request

**Comment by Kampfkarren** [comment] 2018-03-28 21:04
@msciotti I'm reading the page now (it's [here](https://discordapp.com/developers/docs/topics/rpc#setactivity) if anyone else wants a read). This seems to be *exactly* what I want, but the issue is I can't USE the RPC socket!

All HTTP requests on my platform are strictly server-side for security reasons. Does this mean I *still* have no way of setting RPC activity? Is there no hope for a simple opt in for a server to set your activity?

**Comment by msciotti** [comment] 2018-03-28 21:58
I see, so what you're saying is that you can't make a `POST` request to `http://127.0.0.1:PORT/rpc` because it's not running locally, it's server-side only and you'd need something like `https://discordapp.com/api/blahhhhhh/user_id`.

**Comment by Vatuu** [comment] 2018-03-28 22:03
I'd actually love a feature like that too. It'd allow for so much more features, without having to have a copy of the RPC/Rich Presence running locally, especially if all the application is doing is just updating the presence without taking the join/spectate part into consideration.

**Comment by Kampfkarren** [comment] 2018-03-28 22:27
@msciotti Exactly.

**Comment by Tenrys** [comment] 2018-03-28 23:31
@msciotti Does https://github.com/discordapp/discord-rpc/issues/97#issuecomment-377029613 still imply that you need a whitelisted application in order to successfully run the `SET_ACTIVITY` command? Or is there something that I'm doing wrong with my HTTP request, any command I need to run prior?

```lua
local client_id = "428418963836502016"
local discord_rpc = ("http://127.0.0.1:6463/rpc?v=1&client_id=%s&encoding=json"):format(client_id)

local printstuff = function(ctx)
	return function(...)
		print(ctx, ":")
		PrintTable({...})
	end
end

HTTP{
	url = discord_rpc,
	method = "POST",
	success = printstuff("success"),
	failed = printstuff("failed"),
	headers = {
		["Content-Type"] = "application/json"
	},
	body = util.TableToJSON{
		cmd = "SET_ACTIVITY",
		args = {
			pid = 31500, -- Also, does this actually matter for anything?
			activity = {
				state = "Testing",
				details = game.GetMap()
			}
		},
		nonce = tostring(SysTime()),
	}
}
```

Currently this just takes a long time to respond or print this out:
```
failed	:
{
	[1] = "unsuccessful",
}
```

It feels like I'm not very far from pulling it off.

**Comment by msciotti** [comment] 2018-03-28 23:34
@Tenrys: No, you don't need to be whitelisted for the `SET_ACTIVITY` command. You don't need the `encoding` in your url by the way. I did just push the fix for this today, so it may not be ready for testing quite yet.

@Kampfkarren: I see, I misunderstood the first time around then. Unfortunately, I think I'd have to reference back to my original comment in that the way our presence system works simply can't support this without some major changes.

**Comment by Tenrys** [comment] 2018-03-28 23:39
Thanks a lot for your help! I'll wait a little bit before trying this out again then.

**Comment by Kampfkarren** [comment] 2018-03-28 23:42
@msciotti What do you mean by major changes? That RPC isn't just on localhost?

**Comment by Tenrys** [comment] 2018-03-28 23:48
I'm trying `curl` out and it seems to yield different results right now:

```
tenrys@Tenrys:/mnt/c/Users/Tenrys$ curl -X POST -H 'Content-Type: application/json' -d '{"cmd":"SET_ACTIVITY","nonce":"1850.9240138137","args":{"activity":{"state":"Testing","details":"gm_construct_m3_120"},"pid":"31500"}}' http://127.0.0.1:6463/rpc?v=1&client_id=428418963836502016
[1] 40
tenrys@Tenrys:/mnt/c/Users/Tenrys$ {"code":4000,"message":"No Client ID Specified"}
```

Which doesn't makes much sense to me.

**Comment by msciotti** [comment] 2018-03-29 00:13
@Tenrys if you use curl you have to escape char some of the url, like:

`http://127.0.0.1:6463/rpc\?v\=1\&client_id\=428418963836502016`

Something like that. If you set the `-v` flag, you'll see it more clearly that it's chopping your client id from the request without the escape characters.

**Comment by msciotti** [comment] 2018-03-29 00:15
@Kampfkarren our presence system is dependent on communication with the local Discord client. It doesn't currently touch our HTTP API at `discordapp.com/api`, which is what I'm referring to in saying it would require major changes.

**Comment by Tenrys** [comment] 2018-03-29 00:16
Oh thanks. However it gets stuck now: 

```
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 6463 (#0)
> POST /rpc?v=1&client_id=428418963836502016 HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:6463
> Accept: */*
> Content-Type: application/json
> Content-Length: 134
>
* upload completely sent off: 134 out of 134 bytes
```

**Comment by Kampfkarren** [comment] 2018-03-29 00:40
@msciotti That's a bummer. I hope that someday I'll be able to use a server-side HTTP API.

**Comment by Tenrys** [comment] 2018-03-29 00:45
@Kampfkarren Does Roblox not allow sending HTTP requests from the client?

**Comment by Kampfkarren** [comment] 2018-03-29 01:08
@Tenrys No.

**Comment by Tenrys** [comment] 2018-03-29 07:09
Okay so as you said it was just a question of waiting for it to work. It works properly now, although it seems other users need to authenticate when I don't. It's going to be tricky debugging this

**Comment by Tenrys** [comment] 2018-04-02 08:17
It worked before on Canary but it time outs now, yeah. I hope it's going to get fixed and ship with normal Discord.

**Comment by SEAPUNK** [comment] 2018-04-02 20:48
Is it broken on only Canary? Can you check PTB and Stable?

**Comment by Tenrys** [comment] 2018-04-02 20:58
Nothing showed up on Discord Canary, it was just timing out.
Didn't try Stable and PTB but I don't think it'll work, I'll give it a try

**Comment by Tenrys** [comment] 2018-04-02 21:04
Times out on Stable, have to try PTB I guess.

**Comment by Tenrys** [comment] 2018-04-02 21:08
Times out on all builds.

**Comment by SEAPUNK** [comment] 2018-04-02 21:09
Hmm, I'm going to have to bisect this one. Do you have some example code I can run to test this?

**Comment by Tenrys** [comment] 2018-04-02 21:11
`curl -X POST -H 'Content-Type: application/json' -d '{"cmd":"SET_ACTIVITY","nonce":"1850.9240138137","args":{"activity":{"state":"Testing","details":"???"},"pid":12345}}' http://127.0.0.1:6463/rpc\?v\=1\&client_id\=428418963836502016`

This should do the trick?

**Comment by SEAPUNK** [comment] 2018-04-02 21:18
Will test, thanks.

**Comment by Tenrys** [comment] 2018-04-02 21:20
I noticed it broke around the time of last friday, if that helps.

**Comment by morpig** [comment] 2018-04-02 21:39
@SEAPUNK the only thing that shows on Discord's dev console is a request to oauth2/applications/<application_id>/rpc, nothing in the console.

**Comment by SEAPUNK** [comment] 2018-04-02 21:59
Okay, I confirmed that it's my code that broke it. I'll work on a fix; will post updates.

**Comment by SEAPUNK** [comment] 2018-04-02 22:53
Alright, I think I fixed it. I'll push the update to Canary.

**Comment by Tenrys** [comment] 2018-04-02 23:02
Updated, doesn't seem to be much of a difference, unless this is a different update I downloaded somehow

**Comment by SEAPUNK** [comment] 2018-04-02 23:02
Not yet, I'll let you know when it's updated.

**Comment by Tenrys** [comment] 2018-04-02 23:02
Okay, a bit too hasty there I guess.

**Comment by Tenrys** [comment] 2018-04-02 23:07
Updated, works!

**Comment by SEAPUNK** [comment] 2018-04-02 23:09
👌 

PTB and Stable will get updated with the bugfix later, can't give you an ETA.

**Comment by SEAPUNK** [comment] 2018-04-02 23:34
Fixes should be on PTB and Stable now.

**Comment by morpig** [comment] 2018-04-03 10:27
It works now, thanks for the help. Just wondering, does it work via Websocket? Tried it couple minutes ago, but it requires auth to use it.

**Comment by Tenrys** [comment] 2018-06-05 20:16
It looks like the HTTP API broke in a recent update, the client receives the messages you send it, and I can see it in the devtools console but it never updates the presence after you first send it. This is the case on both Canary and Stable branches.
