### ISSUE TITLE
Some joining players don't fire join callbacks.

### ISSUE THREAD

**Issue by StrikerMan780** [discordapp/discord-rpc#52] opened 2017-11-19 06:24 UTC
Seems for some reason, and only for some users, the Discord desktop client doesn't launch my app when they get a "yes" response from it in the join request handler. Even if they have the game registered fully, and added to their "games" list in Discord.

**Comment by StrikerMan780** [comment] 2017-11-19 07:27
Also, I found out that Discord doesn't set the "current working directory" for the launched exe to the folder where the EXE resides, this isn't good.

**Comment by msciotti** [comment] 2017-11-20 17:41
@crmarsh this working directory thing is something that came up during beta. I think you instructed to add something like:

```c
void ChangeToExeDir()
{
    wchar_t exeFilePath[MAX_PATH];
    GetModuleFileNameExW(GetCurrentProcess(), nullptr, exeFilePath, MAX_PATH);
    PathCchRemoveFileSpec(exeFilePath, MAX_PATH);
    SetCurrentDirectoryW(exeFilePath);
}
```

Is this something we should add to the SDK for all developers? Or offer on a case by case basis?

**Comment by StrikerMan780** [comment] 2017-11-21 01:45
That's basically what my program is doing. Sucks though, because it's not portable.

**Comment by crmarsh** [comment] 2017-11-21 19:05
The way we register games (via registering a custom uri handler) make the current dir thing not easy to do. If you need this, perhaps you should register a script that changes the current dir and launches the executable, or do something like the code above.

**Comment by StrikerMan780** [comment] 2017-11-22 00:11
Seems like an issue with Discord itself, since it handles the actual launching. I'll keep the workaround for now.

**Comment by StrikerMan780** [comment] 2017-11-24 02:06
Ok, I got my friend's discord launching games, but... the joinGame callback refuses to fire for him. Many other players don't seem to have any issue.

**Comment by StrikerMan780** [comment] 2017-11-24 03:11
Further testing with several people, shows that some people get the callback, some do not. There's definitely something bugged with Discord or the RPC.

**Comment by devsnek** [comment] 2017-11-24 03:15
you can join the discord api server (discord.gg/discord-api) to get support

**Comment by StrikerMan780** [comment] 2017-11-24 05:29
The same very people who don't get the joinGame callback, also get this when the game launches: https://media.discordapp.net/attachments/379821973850685461/383455414395600901/screen.png?width=1196&height=677

**Comment by night** [comment] 2017-11-26 22:57
If you could post console logs from our client it would help. If the SDK is not connecting to our client it could explain the misbehavior. It's also possible our client RPC server is not spawning properly.

**Comment by StrikerMan780** [comment] 2017-11-27 00:04
How would one get console logs?

**Comment by StrikerMan780** [comment] 2017-11-27 01:06
NVM, got that. Here's the log. ![Image](https://cdn.discordapp.com/attachments/379821973850685461/384509983116492800/screen.png)

**Comment by StrikerMan780** [comment] 2017-11-27 01:08
As you can see, the front-end launches... but it doesn't run the join callback. (Otherwise the frontend would say: Discord: Join, and be launching the game, rather than asking them if they're hosting.)

**Comment by StrikerMan780** [comment] 2017-11-27 21:54
What strikes me as weird, is that the log says launch failed: 1, but the matchmaker indeed launched...

**Comment by msciotti** [comment] 2017-11-28 19:18
@StrikerMan780 we had a bit of a nasty bug in our joining logic that you might have stumbled upon. Can you confirm that you're still seeing this behavior with two up to date Discord clients?

**Comment by StrikerMan780** [comment] 2017-11-29 21:22
I'll give it a shot later tonight.

**Comment by StrikerMan780** [comment] 2017-11-30 02:43
It's not fixed. Still bugged.

**Comment by StrikerMan780** [comment] 2017-11-30 02:47
Also, if my tester uses "Ask to Join", I get this error:

Discord: join request from Noldor Ranzou - <snip>
Accept? (y/n)
> y

Discord: error (4012: no join request for that user)

**Comment by StrikerMan780** [comment] 2017-12-05 05:21
Still nothing? I've had him update Discord multiple times, even doing fresh installs of Discord, both mainline and canary, I've updated the version of the Discord-RPC library and re-compiled my app. I've updated the discord-rpc.dll file included with the app too.

Still broken.
[sigh](https://i.imgur.com/5oorrHR.png)

**Comment by msciotti** [comment] 2017-12-05 05:54
I completed testing with our unity app today and confirm everything worked fine. My next task is updating unreal engine and confirmed that example works as well.

The best thing at this point would probably be to drop me a link to your source code (if it's open) and let me try it myself? Our example implementations work, so it seems like a game-specific issue. I'm happy to take a deeper look at your exact code if you can provide it.

**Comment by StrikerMan780** [comment] 2017-12-05 09:00
https://gitlab.com/mossj32/discord_matchmaker_for_eduke32-oldmp/blob/master/src/DiscordLauncher.cpp

The most important stuff is here.

**Comment by msciotti** [comment] 2017-12-05 18:27
Alright, taking a look now.

Somewhat unrelated, but in your join request handling, you're incrementing `joinedplayers` when you could be responding no to the request:

```c
while (1)
	{
		/* other switch statement logic */
		if (yn[0] == 'y') {
			response = DISCORD_REPLY_YES;
			break;
		}

		if (yn[0] == 'n') {
			response = DISCORD_REPLY_NO;
			break;
		}
	}

	Discord_Respond(request->userId, response);
	joinedplayers++;
```

Unsure if that's intentional, but looked a little weird to me.

**Comment by msciotti** [comment] 2017-12-05 19:10
Your code looks sane. I've cloned your repo and am installing the game to which it connects. Will test locally with a debugger and see what I can find.

**Comment by StrikerMan780** [comment] 2017-12-05 21:39
The latest release of EDuke32-OldMP can be found here:
https://gitlab.com/mossj32/EDuke32-OldMP_Maintenance/tags

You will need a copy of Duke Nukem 3D Atomic Edition's Duke3d.grp file, and put DiscordLauncher.exe in the same folder.

**Comment by msciotti** [comment] 2017-12-05 22:48
OK, so I ended up ripping out the game launching part because it wasn't actually necessary for testing the integration.

I tested with both my home machine:

- Windows 10
- Discord Canary
- VS2015 Community for Debugging

And a freshly installed VM:

- Windows 10
- Discord Stable
- VS2017 Community for Debugging

I can confirm that both clients can successfully send and receive invites, demonstrated in a test here:

https://drive.google.com/file/d/1ng3IUwIWTXIVB_FuIMsbWG3q9M6bqcCD/view?usp=sharing

Sorry, GitHub doesn't like video files.

There are a couple things that look suspicious to me:

```cpp
char js_buffer[512];
/* more stuff */
sprintf(js_buffer, "-g mods\\%s /net /n0 %s", modList[selected_mod - 1], szIp);
/* more stuff */
presence.joinSecret = js_buffer;
```
Depending on the size of this string, it's entirely possible that it's too large for what the payload allows (128 bytes) depending on what gets passed when certain individuals are trying to host. I tried setting the secret to `ThisIsATest` like in the video, and also `-g mods\\amazing /net /0 123.456.7.89` to more mimic an IP like what your code would generate. Both worked fine in testing.

The second thing that gives me pause is:

```cpp
printf("Waiting 2 seconds for a join callback from Discord.\n\n");
	for (int i = 1000 * 2; i > 0; i--)
	{
		Discord_RunCallbacks();
		Sleep(1);
	}
```

I modified this to only wait 2 seconds before prompting. That being said, there were a few occurrences where this was blocking the process for much longer than two seconds. I can't say for sure this would cause an issue, but it may be better to refactor this to be a flow like:

```cpp
bool host = AskToHost();
if (host) { 
    HostGame();
}
else {
    WaitForInvites();
}
```

Rather than blocking the thread.

**Comment by StrikerMan780** [comment] 2017-12-05 23:22
Like I said, it doesn't matter who hosts. This one person can't join ANYONE, EVER, NOBODY, I said this repeatedly, and I'll say it again to be clear: If he hosts, anyone can join him, but if other people hosts, HE CAN NOT JOIN ANYONE. The joinGame callback NEVER fires on his end, EVER.

It doesn't matter the length of the secret, and the code blocks you quoted here, have been changed more than a dozen times for the last two weeks, nothing changes the behavior, at all.

**Comment by StrikerMan780** [comment] 2017-12-06 04:26
OK, this is fucked. In Killing Floor 2, this person can join, no problem. But, no matter what I change, or what order I move things around in my app, and no matter how often I try, this ONE person cannot join in my app. They are a tester in my app, but the join callback still never fires.

**Comment by StrikerMan780** [comment] 2017-12-06 04:43
Ok, I found out that doing this:

```
	printf("Waiting 5 seconds for a join callback from Discord.\n\n");
	for (int i = 1000 * 5; i > 0; i--)
	{
		Discord_RunCallbacks();
		Discord_RunCallbacks();
		Sleep(1);
	}
```
seems to make it work. Really weird.

**Comment by msciotti** [comment] 2017-12-06 16:45
I'm glad that you were able to find a workable solution! Apologies for the frustration it caused. If things seem to work as necessary, I'll close the issue.

I still might council implementing a non-blocking way of letting players listen for callbacks, but if it works, it works!

I'm sure that your players will be very happy with the implementation and increased functionality; it seems like a cool mod for a game you clearly have a lot of passion for!

**Closed by msciotti** 2017-12-06 16:45 UTC
