### ISSUE TITLE
Discord doesn't show the focused RPC game if two games are running at the same time

### ISSUE THREAD

**Issue by Taskkill2187** [discordapp/discord-rpc#217] opened 2018-08-10 20:03 UTC
According to the faq of the documentation here: [https://discordapp.com/developers/docs/rich-presence/faq](url):
"Q: What happens if someone has more than one game running that supports Rich Presence?
Discord will show presence for whichever game is currently focused or was most recently focused."

Well that doesn't seem to happen as you can see on this beautiful screenshot of my 2 screens: ![unbengxziogzoiannt](https://user-images.githubusercontent.com/19777592/43978874-09b7fbdc-9ce9-11e8-8b80-761c29fbab5a.JPG)
Im playing Warframe which is as you can see from the taskbar on the left screen focused but its rpc data isn't shown instead it shows the rpc of the other "game" which is my MusicPlayer.

**Comment by msciotti** [comment] 2018-08-11 20:06
Mmm, it's possible that this changed. We've had a number of internal changes around the presence system to support new stuff we're working on, and swapping back and forth between two "equal" level presences may have broken/been changed.

In what order did you open these apps? Also, in the Discord console (control + shift + i/command + option + i), you should see a log that says `runninggamesstore`. This is an array of executables currently being tracked by your local client. In what order is that array?

**Comment by Taskkill2187** [comment] 2018-08-13 13:51
The MusicPlayer app is basically running all the time so its mostly opened first but rarely has focus. So it was opened first.
I have some experience with that kind of console from other browsers but I couldnt find a `runninggamesstore` yet. All I found was the set activity payload: 
![unbxfigzoenannt](https://user-images.githubusercontent.com/19777592/44035821-aa4bab1a-9f10-11e8-870a-e385a5472e5e.JPG)

**Comment by UrbanCMC** [comment] 2018-08-26 17:56
I've noticed the same thing happening with Discord only ever showing the first application that opened an RPC connection.  

I tried a couple of different applications, starting them in any possible order. The `RunningGameStore` log entry was shown in the log whenever one was opened/closed:
![2018-08-26_discord_richpresence](https://user-images.githubusercontent.com/9725089/44631228-6d95e380-a969-11e8-8e04-e40509c20db7.png)  

In the image above, foobar2000 was started after citra, and the `lastFocused` time also shows that it was most recently focused of the two, but Discord keeps showing Citra's rich presence status.  

This also doesn't change when one or both of the applications send further activity payloads. Everything not sent from Citra is simply ignored.

**Comment by UrbanCMC** [comment] 2018-08-27 16:11
But aren't both of those applications rich presence "games", since they establish a connection using RPC?  

So it's for the time being just a matter of which rich presence game was started first?

**Comment by Taskkill2187** [comment] 2018-09-10 17:01
Oh hi I was gone for a while.
And yeah for me it were two actual rich presence games as well but if we actually get support for multiple rich presences in the future anyway which is really needed imo then it should be fine anyways.
Can you give us some vague release date for that feature?

**Comment by msciotti** [comment] 2018-09-10 17:08
Backend work for multi-presence support already exists, but the front-end client isn't doing anything with it yet. It's not a huge priority right now, but it's something we are working on.

This is working as intended for the current tech, albeit not perfectly for your use case. I'm gonna close this issue and will update documentation accordingly.

**Closed by msciotti** 2018-09-10 17:08 UTC

**Comment by Lyxaaa** [comment] 2023-07-02 03:43
5 years.... and this is still "working as intended"

**Comment by Lachee** [comment] 2023-07-03 02:39
> 5 years.... and this is still "working as intended"

if you have a problem with how things work, you can suggest changes on Discord's official feedback platform. Here is not the place to be asking for platform changes or to be snarky.
