### ISSUE TITLE
Discord_Shutdown doesn't hide rich presence from Discord until the app that called it closes.

### ISSUE THREAD

**Issue by SSStormy** [discordapp/discord-rpc#56] opened 2017-11-20 02:23 UTC
I'm trying to get Discord to hide rich presence when it's not needed by calling Discord_Shutdown. However, this is not hiding rich presence at all. It only goes away after the parent app is closed.

uname -a `Linux justas-main 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux`

**Comment by Mootjuh** [comment] 2017-11-20 09:23
I've noticed this in UE4 too.

**Comment by msciotti** [comment] 2017-11-20 18:19
This happens because Discord is actually looking at the process id to determine when to stop showing presence. `Discord_Shutdown()` just nicely destroys the connection to the local Discord client.

@crmarsh is this a change that will come when we automagically detect the game on `Discord_Initialize()`? Or not with that update?

**Comment by msciotti** [comment] 2017-11-20 18:42
Sorry for ping Chris, seeing now this is a dupe of #13.

**Closed by msciotti** 2017-11-20 18:42 UTC
Labels: enhancement
