### ISSUE TITLE
[Bug] Final builds in Unity crash on startup for x86_64 builds

### ISSUE THREAD

**Issue by coty-crg** [discordapp/discord-rpc#204] opened 2018-07-03 17:00 UTC
Using https://github.com/discordapp/discord-rpc/releases/tag/v3.3.0 

My plugins folder looks like this: https://i.imgur.com/Xlp1QEw.png

The x86 version works fine in final builds when I use the precompiled win32-dynamic\bin\discord-rpc.dll file from this release. But if I use the precompiled win64-dynamic\bin\discord-rpc.dll there is a crash on startup, with no error given. 

The log just shows: 

Fallback handler could not load library game/game_Data/Mono/data-0000020EC363BBC0.dll
Fallback handler could not load library game/game_Data/Mono/data-0000020EAF745050.dll
Fallback handler could not load library game/game_Data/Mono/data-0000020EB5F03040.dll

**Comment by msciotti** [comment] 2018-07-09 16:56
Do you have the right architectures selected for each DLL in the project settings? If you click one of the DLLs in the Unity editor, there should be a little settings panel on the right in which you select for which architecture the DLL is valid. Looks something like this

![image](https://user-images.githubusercontent.com/4193854/42464585-593fd7e6-835e-11e8-9987-b30db64e6d84.png)

**Comment by coty-crg** [comment] 2018-07-11 20:35
I believe they are correct, yes. Here are some screenshots. 

x86: ![image 86](https://i.imgur.com/SiAUBVk.png)
x86_64: ![image 64](https://i.imgur.com/KDHCnlD.png)

**Comment by Lachee** [comment] 2018-07-12 01:37
What version of Unity3D are you using? And are you running .NET 2.0, or .NET 4.6 Experimental? Are you running a 64bit editor? You maybe getting conflicting dll imports, one of them should exclude the editor.

**Comment by coty-crg** [comment] 2018-07-13 00:43
Unity 2017.4.5f1, platform is set to x86 in the editor. It's .NET 2.0. Since they're setup the way they are in the screenshots, since the editor is x86 only that one is loaded in the editor, I believe.

**Comment by Lachee** [comment] 2018-07-15 23:44
I would recommend try recompiling the dlls, and make sure you have the x86 one and a x86_64 one. They cannot be mixed and must be separated in the folders (If you try to run a x86_64 by accident in Unity it will crash for example). 

Make sure you have unity closed during the copy as well, as native libraries stay loaded throughout the lifetime of Unity.

**Comment by coty-crg** [comment] 2018-08-09 18:58
I know about the unity dll stuff, don't know much about python. Following the readme, doing "python build.py unity" - I get the following error message. 

Traceback (most recent call last):
  File "build.py", line 9, in <module>
    import click
ModuleNotFoundError: No module named 'click'

**Comment by msciotti** [comment] 2018-08-09 20:08
@coty-crg just do a quick `pip install click` (might need a sudo in there) and that'll be all good!

**Comment by coty-crg** [comment] 2018-08-10 16:50
Fixed the missing click module, but now this error is thrown instead.

```
--- Building win32-dynamic
Traceback (most recent call last):
  File "build.py", line 304, in <module>
    sys.exit(cli())
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "build.py", line 73, in unity
    ctx.invoke(libs, clean=False, static=False, shared=True, skip_formatter=True, just_release=True)
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "build.py", line 288, in libs
    build_lib('win32-dynamic', generator32, dynamic_options, just_release)
  File "build.py", line 177, in build_lib
    subprocess.check_call(initial_cmake)
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 323, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\coty\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

**Comment by msciotti** [comment] 2018-08-10 18:46
You probably don't have cmake installed. That being said, you should not need to compile these binaries yourself. The release versions are functional (I just tried it myself).

If you try running our unity example in this repo with a set of released DLLs, do you get the same crash issue?

**Comment by dylanh724** [comment] 2018-08-28 07:38
I can confirm the same issue with Unity 5.6:

[Fallback handler could not load library F:/Games/SteamLibrary/steamapps/common/Throne of Lies/ThroneOfLies_Data/Mono/discord-rpc
Fallback handler could not load library F:/Games/SteamLibrary/steamapps/common/Throne of Lies/ThroneOfLies_Data/Mono/.\discord-rpc
Fallback handler could not load library F:/Games/SteamLibrary/steamapps/common/Throne of Lies/ThroneOfLies_Data/Mono/discord-rpc
Fallback handler could not load library F:/Games/SteamLibrary/steamapps/common/Throne of Lies/ThroneOfLies_Data/Mono/libdiscord-rpc
Fallback handler could not load library F:/Games/SteamLibrary/steamapps/common/Throne of Lies/ThroneOfLies_Data/Mono/.\libdiscord-rpc
Fallback handler could not load library F:/Games/SteamLibrary/steamapps/common/Throne of Lies/ThroneOfLies_Data/Mono/libdiscord-rpc](url)

**Comment by Lachee** [comment] 2018-08-28 08:49
@dylanh724 Unity users have a alternate library for rich presence specifically for unity available as a FYI :eyes: 

While playing around with native libraries myself in Unity 5 recently, I learnt that in order to work within the editor, you must copy the native dll outside of the asset folder to the root folder of the unity project. Unity 2017 doesnt seem to have this issue.

**Comment by dylanh724** [comment] 2018-08-28 14:07
> Unity users have a alternate library for rich presence specifically for unity available as a FYI

It's the same DLL files, isn't it? If not, my mind is blown -- let me know where you are talking about ;D

I know I can run rich presence in Unity WITHOUT the dlls IF I'm in Unity, but as soon as I build, I need those DLL's, to my [current] knowledge.

**Comment by Lachee** [comment] 2018-08-28 17:17
Unity will no unload native libraries as a FYI. You have to restart Unity if you make a change and its loaded. They are indeed the correct properties. You should have 2 .dll for both 32bit and 64bit systems. When you do a build Unity will copy these into the correct folders within the build.

@dylanh724 I didnt really want to do this in a commit in another library. But there is alternative C# library within https://github.com/discordapp/discord-rpc#wrappers-and-implementations that is designed for Unity.

**Comment by msciotti** [comment] 2018-08-29 17:09
@Lachee is correct that you can use their C# wrapper. I was not aware that a new Unity version was pushed that changed where plugins are supposed to go?

So am I correct that for compiled builds, the `.dll`s need to go in `Plugins/`, but when running from the Editor they go in the root `Assets/` folder??

**Comment by Lachee** [comment] 2018-08-30 02:45
@msciotti No quiet. In Unity 2017 and 2018 they fixed this bug, but in Unity 5 native libraries need to be copied into `MyProject/`, _outside_ of the `Assets/` folder. They still need to be in the `Plugins` folder too as this is how unity knows how to include them in the build.

**Comment by msciotti** [comment] 2018-08-30 17:06
Oh, Unity 5 is _older_. I thought it was a new release I didn't know about. Well, in that case, this seems like a documentation fix in the ReadMe page. I can do that.

**Comment by msciotti** [comment] 2018-08-30 17:36
Honestly, perhaps I'm missing something here @Lachee. I've tested both 32 and 64bit builds using both:

`Unity 2018.2.5f1`
`Unity 5.6.6f2`

Targeting the exact same project with files and folders set up mirroring the Unity example in this repo; that is to say, within the `Plugins/` folder but not in the root directory of the project.

In neither case have I been able to reproduce this. Is there a piece I'm missing here?

@dylanh724 states he's using Unity 5, and @coty-crg using 2017. Both have these issues, but I cannot reproduce on either.

**Comment by Lachee** [comment] 2018-08-30 23:12
I thought there was a distinction. I know that my native library has to be copied out for Unity 5 and with my other projects the steamworks native dll have to be copied out. I will experiment with this more tonight and give a definite answer. Unity always has been strange with its dlls.

**Comment by Lachee** [comment] 2018-09-02 10:27
Alright @msciotti seems like I was wrong. My bad. The discord library does _not_ have to be copied into the root, that seems like that was just a oddity with other libraries I deal with. I have tried with Unity 5, 2017, and 2018 and they all ran fine without any extra moving and they build versions worked just fine.

As you said, just the import configs have to be correct, make sure only the 32bit is available on 32bit builds and 64bit available on 64bit builds and they are in the correct folders (which the build script included in the clicker example has).

**Comment by msciotti** [comment] 2018-09-02 20:08
Thank you so much for debugging help. Sometimes I think I'm going crazy trying to repro this issues :blobsweats:

I'm going to close this issue for now. This seems like an oddity in whatever state these specific Unity editors have gotten themselves into. With the recent Unity-specific DLL explanations in the Readme, I think others should be able to use this just fine. If the users here are still experiencing issues, I'd recommend ripping out the Discord DLLs from their project and trying to import them again from scratch.

**Closed by msciotti** 2018-09-02 20:08 UTC
