### ISSUE TITLE
Feature Request - A callback for the host when a player joins game through discord.

### ISSUE THREAD

**Issue by GamerUntouch** [discordapp/discord-rpc#81] opened 2017-12-03 16:47 UTC
When a player joins through discord (through invite), they get an onJoin() callback, but the host doesn't get any callback to let them know that the invite was accepted or that someone has joined the game. I can think of a couple uses for this, besides just convenience. 
Maybe it does exist already but I don't see it.

Thanks.

**Comment by msciotti** [comment] 2017-12-03 18:16
Duplicate of #62. I'll reference night's comment here:

https://github.com/discordapp/discord-rpc/issues/62#issuecomment-347044822

The TL;DR is that your server/matchmaking/party implementation should be aware of when new players join the game instance and update everyone's presence accordingly.

I'm going to close this issue, but if you can lay out concrete reasons as to why this feature should exist that cannot be accomplished through your own infrastructure, I'm happy to read 'em.

**Closed by msciotti** 2017-12-03 18:16 UTC
